In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 0, 0, 1, 0, 0, 0, 0.3, 0.3, 0.3, 0, 13, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 14, 1, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 16, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0.5, 0.5, 5, 0, 0, 0 ,   0],
    [0, 1, 0, 0, 0, 0, 1, 0, 0, 0.5, 0.5, 8, 0, 0, 1,    0],
    [0, 0, 1, 1, 0, 0, 0, 0.5, 0, 0.5, 0, 9, 0, 0, 0,    0],
    [0, 0, 1, 0, 0, 1, 0, 0.5, 0, 0.5, 0, 12, 1, 0, 0,   0]
])

In [3]:
Y = np.array([
    [5],
    [3],
    [1],
    [4],
    [5],
    [1],
    [5]
])

In [4]:
def initialize_weights(X, k):
    W0 = 0
    W = np.zeros((1, X.shape[1]))
#     V = np.zeros((X.shape[1], k))
    V = np.random.normal(0, 0.0001, ((X.shape[1], k)))
    return W0, W, V

In [5]:
def forward_prop(W0, W, X, V):
    linear_term = W0 + np.dot(X, W.T)
    interactions = 0.5*np.sum((np.dot(X, V) - np.dot(X**2, V**2)), 1, keepdims=True)
#     print(interactions)
    y_hat = linear_term + interactions
    return y_hat

In [6]:
def cost_function(y, y_hat):
    cost = 0.5*(y - y_hat)**2
    return cost

In [7]:
def backprop(y, y_hat, X, V):
    first_term = np.dot(X, V)
    first_term = np.broadcast_to(first_term, (X.shape[1], V.shape[1]))
    first_term = first_term * X.T
    
    second_term = V * (X.T)**2
    
    d_interactions = first_term - second_term
    
    d_W0 = -(y - y_hat)
    
    d_W = -(y - y_hat) * X
    
    d_V = -(y - y_hat) * d_interactions
    
    return d_W0, d_W, d_V
    

In [8]:
def update_weights(w0, w, v, learning_rate, dw0, dw, dv):
    w0 -= learning_rate*dw0
    w -= learning_rate*dw
    v -= learning_rate*dv
    return w0, w, v

In [9]:
def model(X, Y, k, no_of_iters=1, learning_rate=0.1):
    cost = []
    w0, w, v = initialize_weights(X, k)
    for j in range(no_of_iters):
        for i in range(len(X)): #ie: X[0], X[1],......X[m]
            y_hat = forward_prop(w0, w, X[i].reshape(1, X.shape[1]), v)
            loss = cost_function(Y[i].reshape(1, 1), y_hat)
            cost.append(loss)
            dw0, dw, dv = backprop(Y[i].reshape(1,1), y_hat, X[i].reshape(1, X.shape[1]), v)
            w0, w, v = update_weights(w0, w, v, learning_rate, dw0, dw, dv)
    
    return w0, w, v, cost

In [10]:
w0, w, v, cost = model(X, Y, k=3, no_of_iters=30, learning_rate=0.001)

In [11]:
w0, w, v

(array([[0.11900954]]),
 array([[-0.06829775,  0.16808624,  0.01922105,  0.01028054, -0.11881657,
          0.13996213,  0.08758344, -0.0108788 , -0.02048932,  0.07316432,
          0.08404312,  0.2603057 ,  0.03442074, -0.09377798,  0.08758344,
          0.        ]]),
 array([[ 5.87525289e-04,  6.75060151e-04, -6.31753425e-04],
        [-4.70793202e-04, -7.77810358e-04,  3.83605743e-04],
        [-3.25492813e-05, -6.90715811e-05,  2.29404983e-04],
        [-1.70859332e-04,  1.90754033e-05,  1.42687151e-04],
        [ 9.07397530e-04,  1.38106093e-03, -6.08050962e-04],
        [-5.86945788e-04, -1.04299856e-03,  5.39366293e-04],
        [-4.83081410e-04, -6.01190978e-04,  2.43294258e-04],
        [ 7.42075850e-05,  2.40180798e-04, -8.03779528e-06],
        [ 1.81653185e-04,  8.35618221e-05, -2.35044688e-04],
        [-2.65399649e-04, -3.73215021e-04,  2.31403649e-04],
        [-9.32402906e-05, -5.79806831e-04,  2.21878632e-04],
        [-1.52592510e-03, -2.42113291e-03,  1.37026234e-03

In [12]:
forward_prop(w0, w, X[6].reshape(1, 16), v)

array([[3.45072191]])

In [13]:
cost

[array([[12.50243607]]),
 array([[2.1609365]]),
 array([[0.13696699]]),
 array([[6.35129659]]),
 array([[8.6343775]]),
 array([[0.03233362]]),
 array([[5.65474978]]),
 array([[3.63060366]]),
 array([[0.00021713]]),
 array([[2.87393815]]),
 array([[4.8147383]]),
 array([[5.96702653]]),
 array([[0.47700778]]),
 array([[3.07128758]]),
 array([[1.78407652]]),
 array([[0.24212205]]),
 array([[4.64379156]]),
 array([[4.29443617]]),
 array([[5.11252529]]),
 array([[0.75859107]]),
 array([[2.34064638]]),
 array([[1.29475133]]),
 array([[0.44398245]]),
 array([[5.34157394]]),
 array([[4.08813871]]),
 array([[4.79424461]]),
 array([[0.87494657]]),
 array([[2.09843599]]),
 array([[1.14582144]]),
 array([[0.52418918]]),
 array([[5.57457796]]),
 array([[3.98665486]]),
 array([[4.65147854]]),
 array([[0.9199757]]),
 array([[2.00740765]]),
 array([[1.09975029]]),
 array([[0.54885287]]),
 array([[5.63422219]]),
 array([[3.92143921]]),
 array([[4.56883407]]),
 array([[0.93830229]]),
 array([[1.96687816