In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 0, 0, 1, 0, 0, 0, 0.3, 0.3, 0.3, 0, 13, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 14, 1, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 16, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0.5, 0.5, 5, 0, 0, 0 ,   0],
    [0, 1, 0, 0, 0, 0, 1, 0, 0, 0.5, 0.5, 8, 0, 0, 1,    0],
    [0, 0, 1, 1, 0, 0, 0, 0.5, 0, 0.5, 0, 9, 0, 0, 0,    0],
    [0, 0, 1, 0, 0, 1, 0, 0.5, 0, 0.5, 0, 12, 1, 0, 0,   0]
])

In [3]:
Y = np.array([
    [5],
    [3],
    [1],
    [4],
    [5],
    [1],
    [5]
])

In [4]:
def initialize_weights(X, k):
    W0 = 0
    W = np.zeros((1, X.shape[1]))
#     V = np.zeros((X.shape[1], k))
    V = np.random.normal(0, 0.0001, ((X.shape[1], k)))
    return W0, W, V

In [5]:
def forward_prop(W0, W, X, V):
    linear_term = W0 + np.dot(X, W.T)
    interactions = 0.5*np.sum((np.dot(X, V) - np.dot(X**2, V**2)), 1, keepdims=True)
#     print(interactions)
    y_hat = linear_term + interactions
    return y_hat

In [6]:
def cost_function(y, y_hat):
    cost = 0.5*(y - y_hat)**2
    return cost

In [7]:
def backprop(y, y_hat, X, V):
    first_term = np.dot(X, V)
    first_term = np.broadcast_to(first_term, (X.shape[1], V.shape[1]))
    first_term = first_term * X.T
    
    second_term = V * (X.T)**2
    
    d_interactions = first_term - second_term
    
    d_W0 = (y - y_hat)
    
    d_W = (y - y_hat) * X
    
    d_V = (y - y_hat) * d_interactions
    
    return d_W0, d_W, d_V
    

In [8]:
def update_weights(w0, w, v, learning_rate, dw0, dw, dv):
    w0 -= learning_rate*dw0
    w -= learning_rate*dw
    v -= learning_rate*dv
    return w0, w, v

In [9]:
def model(X, Y, k, no_of_iters=1, learning_rate=0.1):
    cost = []
    w0, w, v = initialize_weights(X, k)
    for j in range(no_of_iters):
        for i in range(len(X)): #ie: X[0], X[1],......X[m]
            y_hat = forward_prop(w0, w, X[i].reshape(1, X.shape[1]), v)
            loss = cost_function(Y[i].reshape(1, 1), y_hat)
            cost.append(loss)
            dw0, dw, dv = backprop(Y[i].reshape(1,1), y_hat, X[i].reshape(1, X.shape[1]), v)
            w0, w, v = update_weights(w0, w, v, learning_rate, dw0, dw, dv)
    
    return w0, w, v, cost

In [10]:
w0, w, v, cost = model(X, Y, k=3, no_of_iters=10, learning_rate=0.0001)

In [11]:
w0, w, v

(array([[-0.03751262]]),
 array([[-0.0161411 , -0.01138736, -0.00998417, -0.0097358 , -0.00910168,
         -0.01220472, -0.00647042, -0.00983441, -0.00484233, -0.01552809,
         -0.00569368, -0.41455187, -0.01261596, -0.0037735 , -0.00647042,
          0.        ]]),
 array([[-3.43422403e-05,  1.16895300e-04,  7.98148783e-05],
        [ 2.02623650e-05,  5.51625027e-05,  4.40048178e-05],
        [-1.71436106e-04,  1.11820562e-04,  2.43084979e-05],
        [ 6.42149290e-05, -2.29898497e-05, -1.15944964e-04],
        [ 5.38890561e-05,  9.56494906e-05, -5.84966123e-05],
        [ 1.30148879e-04, -1.72160875e-05, -6.16839892e-06],
        [ 1.10128789e-04,  8.98377137e-05, -2.21051069e-05],
        [ 1.59298990e-05, -4.40184273e-05, -7.73022632e-05],
        [-3.16776573e-05, -4.81963767e-05, -2.44425663e-04],
        [ 1.47374713e-04,  1.70510742e-05, -2.21390960e-05],
        [-1.08019636e-04, -2.09772647e-04,  2.02000924e-05],
        [ 1.37678136e-04, -7.80907141e-05,  2.91860130e-0

In [17]:
forward_prop(w0, w, X[6].reshape(1, 16), v)

array([[-5.05915157]])