In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 0, 0, 1, 0, 0, 0, 0.3, 0.3, 0.3, 0, 13, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 14, 1, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 16, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0.5, 0.5, 5, 0, 0, 0 ,   0],
    [0, 1, 0, 0, 0, 0, 1, 0, 0, 0.5, 0.5, 8, 0, 0, 1,    0],
    [0, 0, 1, 1, 0, 0, 0, 0.5, 0, 0.5, 0, 9, 0, 0, 0,    0],
    [0, 0, 1, 0, 0, 1, 0, 0.5, 0, 0.5, 0, 12, 1, 0, 0,   0]
])

In [3]:
Y = np.array([
    [5],
    [3],
    [1],
    [4],
    [5],
    [1],
    [5]
])

In [4]:
def initialize_weights(X, k):
    W0 = 0
    W = np.zeros((1, X.shape[1]))
#     V = np.zeros((X.shape[1], k))
    V = np.random.normal(0, 0.0001, ((X.shape[1], k)))
    return W0, W, V

In [5]:
def forward_prop(W0, W, X, V):
    linear_term = W0 + np.dot(X, W.T)
    interactions = 0.5*np.sum((np.dot(X, V) - np.dot(X**2, V**2)), 1, keepdims=True)
    print(interactions)
    y_hat = linear_term + interactions
    return y_hat

In [6]:
def cost_function(y, y_hat):
    cost = 0.5*(y - y_hat)**2
    return cost

In [7]:
def backprop(y, y_hat, X, V):
    first_term = np.dot(X, V)
    first_term = np.broadcast_to(first_term, (X.shape[1], V.shape[1]))
    first_term = first_term * X.T
    
    second_term = V * (X.T)**2
    
    d_interactions = first_term - second_term
    
    d_W0 = (y - y_hat)
    
    d_W = (y - y_hat) * X
    
    d_V = (y - y_hat) * d_interactions
    
    return d_W0, d_W, d_V
    

In [8]:
def update_weights(w0, w, v, learning_rate, dw0, dw, dv):
    w0 -= learning_rate*dw0
    w -= learning_rate*dw
    v -= learning_rate*dv
    return w0, w, v

In [9]:
X_row_single =X[1].reshape(1, X.shape[1])
X_row_single

array([[ 1. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0.3,  0.3,  0.3,  0. ,
        14. ,  1. ,  0. ,  0. ,  0. ]])

In [10]:
y_row_single = Y[1].reshape(1,1)
y_row_single

array([[3]])

In [11]:
w0, w, v = initialize_weights(X_row_single, k=2)

In [12]:
w0

0

In [13]:
w.shape #1, n

(1, 16)

In [14]:
v.shape #n,2

(16, 2)

In [15]:
y_hat = forward_prop(W0=w0, W=w, X=X_row_single, V=v)
y_hat

[[0.00042392]]


array([[0.00042392]])

In [16]:
d_w0, d_w, d_v = backprop(y= y_row_single, y_hat=y_hat, X=X_row_single, V=v)

In [17]:
d_w0

array([[2.99957608]])

In [18]:
d_w #1,n

array([[ 2.99957608,  0.        ,  0.        ,  0.        ,  2.99957608,
         0.        ,  0.        ,  0.89987282,  0.89987282,  0.89987282,
         0.        , 41.99406512,  2.99957608,  0.        ,  0.        ,
         0.        ]])

In [19]:
d_v #n, k

array([[-0.00096458,  0.00343642],
       [-0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.00064553,  0.00342895],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.0002797 ,  0.00105717],
       [-0.00023046,  0.00104166],
       [-0.00029181,  0.00110442],
       [ 0.        ,  0.        ],
       [-0.00269738, -0.00500769],
       [-0.00140498,  0.00398744],
       [ 0.        ,  0.        ],
       [-0.        ,  0.        ],
       [-0.        ,  0.        ]])

In [20]:
def model(X, Y, k, no_of_iters=1, learning_rate=0.1):
    cost = []
    w0, w, v = initialize_weights(X, k)
    for j in range(no_of_iters):
        for i in range(len(X)): #ie: X[0], X[1],......X[m]
            y_hat = forward_prop(w0, w, X[i].reshape(1, X.shape[1]), v)
            loss = cost_function(Y[i].reshape(1, 1), y_hat)
            cost.append(loss)
            dw0, dw, dv = backprop(Y[i].reshape(1,1), y_hat, X[i].reshape(1, X.shape[1]), v)
            w0, w, v = update_weights(w0, w, v, learning_rate, dw0, dw, dv)
    
    return w0, w, v, cost

In [21]:
w0, w, v, cost = model(X, Y, k=2)

[[-0.00171773]]
[[0.00314257]]
[[-7.00321608]]
[[-14994520.22282087]]
[[-5.81556579e+19]]
[[-1.32865084e+61]]
[[-2.94415042e+181]]


/home/shree/personal_projects/Click-Through-Rate/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in square
  
