In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 0, 0, 1, 0, 0, 0, 0.3, 0.3, 0.3, 0, 13, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 14, 1, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0.3, 0.3, 0.3, 0, 16, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0.5, 0.5, 5, 0, 0, 0 ,   0],
    [0, 1, 0, 0, 0, 0, 1, 0, 0, 0.5, 0.5, 8, 0, 0, 1,    0],
    [0, 0, 1, 1, 0, 0, 0, 0.5, 0, 0.5, 0, 9, 0, 0, 0,    0],
    [0, 0, 1, 0, 0, 1, 0, 0.5, 0, 0.5, 0, 12, 1, 0, 0,   0]
])

In [3]:
Y = np.array([
    [5],
    [3],
    [1],
    [4],
    [5],
    [1],
    [5]
])

In [4]:
def initialize_weights(X, k):
    W0 = 0
    W = np.zeros((1, X.shape[1]))
    V = np.zeros((X.shape[1], k))
    
    return W0, W, V

In [5]:
def forward_prop(W0, W, X_row_single, V):
    linear_term = W0 + np.dot(X_row_single, W.T)
    interactions = 0.5*np.sum((np.dot(X_row_single, V) - np.dot(X_row_single**2, V**2)), 1, keepdims=True)
    y_hat = linear_term + interactions
    return y_hat

In [6]:
def cost_function(y_row_single, y_hat_row_single):
    cost = 0.5(y_row_single - y_hat_row_single)**2
    return cost

In [7]:
def backprop(y_row_single, y_hat_row_single, X_row_single, V):
    first_term = np.dot(X_row_single, V)
    first_term = np.broadcast_to(first_term, (X_row_single.shape[1], V.shape[1]))
    first_term = first_term * X_row_single.T
    
    second_term = (X_row_single.T)**2 * V
    
    d_interactions = first_term - second_term
    
    d_W0 = (y_row_single - y_hat_row_single)
    
    d_W = (y_row_single - y_hat_row_single) * X_row_single
    
    d_V = (y_row_single - y_hat_row_single) * d_interactions
    
    return d_W0, d_W, d_V
    

In [8]:
def update_weights(cost, d_W0, d_W, d_V):
    W0 -= d_W0
    W -= dW
    V -= d_V
    return W0, W, V

In [9]:
X_row_single =X[1].reshape(1, X.shape[1])
X_row_single

array([[ 1. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0.3,  0.3,  0.3,  0. ,
        14. ,  1. ,  0. ,  0. ,  0. ]])

In [10]:
y_row_single = Y[1].reshape(1,1)
y_row_single

array([[3]])

In [11]:
w0, w, v = initialize_weights(X_row_single, k=2)

In [12]:
w0

0

In [13]:
w.shape #1, n

(1, 16)

In [14]:
v.shape #n,2

(16, 2)

In [15]:
y_hat = forward_prop(W0=w0, W=w, X_row_single=X_row_single, V=v)
y_hat

array([[0.]])

In [16]:
d_w0, d_w, d_v = backprop(y_row_single= y_row_single, y_hat_row_single=y_hat, X_row_single=X_row_single, V=v)

In [17]:
d_w0

array([[3.]])

In [18]:
d_w #1,n

array([[ 3. ,  0. ,  0. ,  0. ,  3. ,  0. ,  0. ,  0.9,  0.9,  0.9,  0. ,
        42. ,  3. ,  0. ,  0. ,  0. ]])

In [19]:
d_v #n, k

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])